### ISSUE TITLE
[Feature] 1.17 Update Checklist

### ISSUE THREAD

**Issue by DaFuqs** [DaFuqs/StarrySky#9]
A list of features in 1.17 that should be suported in Starry when updating:

**Blocks / Structures:**
- Amethyst Geodes, Budding Amethyst, Amethyst Buds, Amethyst Clusters, Calcite, Smooth Basalt => New Spheroid Type
- Copper Ore => Additional Ore Spheroid
- Dripstone + Dripstone Blocks, Pointed Dripstone
- Powder Snow
- Tinted Glass (Very rare)
- The Deep Dark => New Structure Sphere Type
- Azalea trees (without blossoms / pink blossoms)
- Glow Lichen (all caves)
- Rooted Dirt
- Hanging Roots (under Rooted Dirt)
- Lush Caves: Cave Vines, Moss, Dripleaf, Spore Blossoms
- Tuff
- New Ore Spheres: Deepslate, Cobbled Deepslate, Deepslate Ores
- Infested Deepslate

**New Mobs:**
- Goats
- Glow Squids
- Axolotl

**Advancements for Sphere types:**
- Amethyst Geode
- Copper Ore
- Dripstone Sphere
- Lush Cave Sphere
- Tinted Glass Sphere
- Azalea Sphere (+rooted Dirt?)
- Tuff Sphere
- Deepslate Spheres?
- Infested Deepslate?

**Feature changes / additions:**
- Move Spheroid definitions to json?
- Test Different world heights via vanillas new json dimension definitions, if functional. Otherwise WorldHeightBooster. (Great suggestion by @Noaaan)
-

**Comment by DaFuqs** [comment]
**Blocks / Structures:**

- [WIP]     Amethyst Geodes, Budding Amethyst, Amethyst Buds, Amethyst Clusters, Calcite, Smooth Basalt => New Spheroid Type
- [x]     Copper Ore => Additional Ore Spheroid
- [x]     Dripstone + Dripstone Blocks, Pointed Dripstone
- [x]     Powder Snow
- [x]     Tinted Glass (Very rare)
- [x]     Azalea trees (without blossoms / pink blossoms)
- [ ]     Glow Lichen (all caves)
- [x]     Rooted Dirt
- [x]     Hanging Roots (under Rooted Dirt)
- [ ]     Lush Caves: Cave Vines, Moss, Dripleaf, Spore Blossoms
- [x]     Tuff
- [x]     New Ore Spheres: Deepslate, Cobbled Deepslate, Deepslate Ores
- [x]     Infested Deepslate

**New Mobs:**

- [ ]     Goats
- [ ]     Glow Squids
- [ ]     Axolotl

**Advancements for Sphere types:**

- [ ]     Amethyst Geode
- [ ]     Copper Ore
- [ ]     Dripstone Sphere
- [ ]     Lush Cave Sphere
- [ ]     Tinted Glass Sphere
- [ ]     Azalea Sphere (+rooted Dirt?)
- [ ]     Tuff Sphere
- [ ]     Deepslate Spheres?
- [ ]     Infested Deepslate?

**Comment by DaFuqs** [comment]
Since lush caves are not yet implemented in 1.17... done!
